server:
  port: 8003
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

aliyun:
  vod:
    file:
      keyid: keyid
      keysecret: keysecret
