server:
  port: 8222

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 使用服务发现路由
      routes:
        - id: service-acl # 路由id
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/** # 路径匹配
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/eduService/** # 路径匹配
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/eduUcenter/** # 路径匹配
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/eduCms/** # 路径匹配
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/eduMsm/** # 路径匹配
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/eduOrder/** # 路径匹配
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/eduOss/** # 路径匹配
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/staService/** # 路径匹配
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/eduVod/** # 路径匹配