server:
  port: 8004

# spring设置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 15159352857
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 1800000
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

#配置mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/yjh/educms/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志