server:
  port: 8160 #服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: service-ucenter
  # mysql数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 15159352857
  redis:
    host: 192.168.200.130
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/yjh/educenter/mapper/xml/*.xml
  # mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wx:
  open:
    # 微信开放平台 appid
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirect_url: http://localhost:8160/api/ucenter/wx/callback