server:
  port: 8005 #服务端口

spring:
  application:
    name: service-msm
# mysql数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 15159352857
  redis:
    host: 192.168.200.130
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/yjh/eduservice/mapper/xml/*.xml
# mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl