server:
  port: 8007 # 服务端口
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 15159352857
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#配置mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath:com/yjh/staservice/mapper/xml/*.xml
# mybatis日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 开启熔断机制
#feign:
#  hystrix:
#    enabled: true

# 设置hystrix超时时间，默认1000ms
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
