spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  profiles:
    active: dev # 环境设置：dev、test、prod
  application:
    name: service-oss

server:
  port: 8002 # 端口

#阿里云oss
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: keyid
      keysecret: keysecret
      bucketname: edu-mikuo
