spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  profiles:
    active: dev # 环境设置：dev、test、prod
  application:
    name: service-oss

server:
  port: 8002 # 端口

#阿里云oss
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI5tQ3jkgcJP4YCoDZQ58K
      keysecret: 2izdliY5Ef7psxpkC972WvfPO0ZNCC
      bucketname: edu-mikuo